---
- name: Create the controller database user
  community.postgresql.postgresql_user:
    login_host: 127.0.0.1
    login_port: '{{ postgresql_port }}'
    login_user: '{{ postgresql_admin_user }}'
    login_password: '{{ postgresql_admin_password }}'
    login_db: postgres
    name: '{{ controller_pg_user }}'
    password: '{{ controller_pg_password }}'

- name: Create the controller database
  community.postgresql.postgresql_db:
    login_host: 127.0.0.1
    login_port: '{{ postgresql_port }}'
    login_user: '{{ postgresql_admin_user }}'
    login_password: '{{ postgresql_admin_password }}'
    name: '{{ controller_pg_database }}'
    owner: '{{ controller_pg_user }}'
