---
- name: Create gateway podman secrets
  containers.podman.podman_secret:
    name: '{{ item.name }}'
    data: '{{ item.data }}'
    skip_existing: true
  loop:
    - { name: gateway_secret_key, data: '{{ gateway_secret_key }}' }
    - { name: gateway_admin_password, data: '{{ admin_password }}' }
    - { name: gateway_db_password, data: '{{ gateway_pg_password }}' }
    - { name: gateway_redis_url, data: '{{ _gateway_redis_url }}' }
  loop_control:
    label: '{{ item.name }}'
  no_log: true
